general {
  lock_cmd = pidof swaylock >/dev/null || swaylock -fF --config ~/.config/swaylock/config
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
  inhibit_sleep = 3
  ignore_dbus_inhibit = false
}

listener {
  timeout = 300
  on-timeout = pidof swaylock >/dev/null || swaylock -fF --config ~/.config/swaylock/config
}

listener {
  timeout = 360
  on-timeout = hyprctl dispatch dpms off
  on-resume = hyprctl dispatch dpms on
}
