# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Keep prompts compact (no blank line above the first prompt)
add_newline = false
format = "$all"
